openapi: 3.0.3
info:
  title: Your API Title
  description: Description of your API
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Production server
paths:
  /endpoint:
    get:
      summary: Retrieve data from the endpoint
      description: Optional detailed description of the operation
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The ID of the resource
                  name:
                    type: string
                    description: The name of the resource
    post:
      summary: Create a new resource
      description: Optional detailed description of the operation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the resource
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                profileImage:
                  type: string
                  format: binary
      responses:
        '201':
          description: Resource created successfully
        '400':
          description: Invalid request