openapi: 3.1.0
info:
  version: 1.0.0
  title: Swagger Petstore 3
servers:
  - url: 'http://petstore.swagger.io/v1'
paths:
  /pets:
    get:
      summary: List all pet
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: An paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
        default:
          description: unexpected error
      description: ''
      security:
        - API Key - 1: []
  /users/picture:
    post:
      summary: Upload a user's picture
      operationId: userPicture
      tags:
        - pets
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                profileImage:
                  type: string
                  format: binary
      responses:
        '200':
          description: Picture Uploaded
        '404':
          description: User not found

components:
  schemas:
    User:
      title: User
      type: object
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
        abc:
          type: array
          x-stoplight:
            id: 0f8du6jplg3dp
          items:
            x-stoplight:
              id: j3lblnblu8ukl
            type: string
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
    Account:
      title: Account
      x-stoplight:
        id: gau90yo9u7t4a
      type: object
      properties:
        id:
          type: string
          description: |-
            asjdkashfj
            **sasd**
      required:
        - id
x-extension-1: ghgh
x-internal: false
security:
  - Access Token: []
  - API Key - 1: []
